/**
 * @packageDocumentation
 * @module api.functional.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from '@nestia/fetcher'
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher'

import type { HealthCheckResult } from '../../structures/HealthCheckResult'

/**
 * @tag Health
 * @summary Health Check
 * @controller HealthController.check
 * @path GET /health
 * @accessor api.functional.health.check
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function check(connection: IConnection): Promise<check.Output> {
  return PlainFetcher.fetch(connection, {
    ...check.METADATA,
    template: check.METADATA.path,
    path: check.path(),
  })
}
export namespace check {
  export type Output = HealthCheckResult

  export const METADATA = {
    method: 'GET',
    path: '/health',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 200,
  } as const

  export const path = () => '/health'
}
