/**
 * @packageDocumentation
 * @module api.functional.post
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from '@nestia/fetcher'
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher'
import type { Format } from 'typia/lib/tags/Format'
import type { MaxLength } from 'typia/lib/tags/MaxLength'
import type { MinLength } from 'typia/lib/tags/MinLength'

import type { Pick__typetitleemailbody } from '../../structures/Pick__typetitleemailbody'

/**
 * @summary Create post
 * @returns Newly created post
 * @tag DemoPrima
 * @operationId createPost
 * @security bearer
 * @controller ExamplePrimaController.createPost
 * @path POST /post
 * @accessor api.functional.post.createPost
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createPost(
  connection: IConnection,
  { body, email, title }: createPost.Body,
): Promise<createPost.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        'Content-Type': 'application/json',
      },
    },
    {
      ...createPost.METADATA,
      template: createPost.METADATA.path,
      path: createPost.path(),
    },
    { body, email, title },
  )
}
export namespace createPost {
  export type Body = Pick__typetitleemailbody
  export type Output = {
    id: number
    title: string & MinLength<5> & MaxLength<80>
    email: string & Format<'email'>
    body: string
    updatedAt: string & Format<'date-time'>
    createdAt: string & Format<'date-time'>
  }

  export const METADATA = {
    method: 'POST',
    path: '/post',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: 201,
  } as const

  export const path = () => '/post'
}
